seratch/AWScala

src/main/scala/awscala/s3/Bucket.scala, src/main/scala/awscala/s3/S3.scala
Enable S3 to list the sub-directories and objects under one directory. Use `"/"` as delimiter.
This is more efficient and convenient than listing all the keys under a prefix and finding the directories in a single level.
Here I use [ListObjectsRequest](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ListObjectsRequest.html) to implement this feature.
Below is an example to list sub-directories and objects' names under `foo/`:
```scala
s3.ls(bucket, "foo/").foreach {
case Left(dir) => println("dir: " + dir)
case Right(obj) => println("obj: " + obj.getKey)
}
```
=> add function ls for S3

src/main/scala/awscala/ec2/InstanceType.scala
Completed the list of instance types. Now all instance types from the Amazon Java SDK are included. This fixes #69.
=> Add latest generation instance types

src/main/scala/awscala/s3/S3.scala
Fix includes a workaround that maps between the region string accepted by the AWS S3 SDK and those accepted by the AWS Core SDK for the us-east-1 region.
=> Resolved #70: Now S3 requests in the us-east-1 region work with provided workaround.

build.sbt, project/Build.scala, project/plugins.sbt
Upgrade to sbt-sonatype-0.5.0, which makes simpler the sbt settings. Major changes include: 
- sbt-sonatype is now an auto-plugin: `sonatypeSettings` (e.g., `publishTo`, `sonatypeRelease` commands, etc.) are automatically loaded.
- `profileName` is prefixed with `sonatype`
=> Upgrade to sbt-sonatype-0.5.0

src/main/scala/awscala/ec2/EC2.scala
If the instance is in pending state, `_.state.getName` will get value `"pending"`, but the value of `aws.model.InstanceStateName.Pending.name()` is always `"Pending"`, hence `awaitInstances` will never wait for the instances to be ready.
=> fix the bug that awaitInstances doesn't wait since pending != Pending

project/Build.scala, src/main/scala/awscala/dynamodbv2/DynamoDB.scala, src/main/scala/awscala/dynamodbv2/Table.scala
Allows reverse sorted results on the primary index. This also adds the method to the table class for both query and queryWithIndex.
=> Add scan index forward argumnet

src/main/scala/awscala/dynamodbv2/AttributeValue.scala, src/test/scala/awscala/DynamoDBV2Spec.scala
I'd be interested in your thoughts on this draft.
It allows passing arbitrarily nested maps to `AttributeValue` to make use of dynamo's [new map/document support](http://aws.amazon.com/blogs/aws/dynamodb-update-json-and-more/).
Right now this is accomplished by coercing any leaf values to string using .toString, but pending review I can generalize it out to other leaf types (keeping the string/number/bytes convention of dynamo)
=> Add support for document maps

src/main/scala/awscala/s3/S3.scala
Changes:
- Better apply reuse in S3 object.
- Add support for specifying the `ClientConfiguration` for S3.
Resolves: #92
I also looked into automatically generating a `ClientConfiguration`, which would eliminate half the apply methods. Unfortunately, there is no public code in the AWS SDK that could be reused, from what I could find.
=> S3 ClientConfiguration support

src/main/scala/awscala/s3/Bucket.scala, src/main/scala/awscala/s3/S3.scala, src/main/scala/awscala/s3/S3Object.scala
AWS limits the batch deletion of S3 objects to 1000 objects per
request. The list of S3 objects gets grouped into buckets of up
to 1000 objects, each of the buckets generates is handled within
a separate deletion request.
The creation of S3 objects based on summary streams has been
simplified to support batch deletion patterns:
val bucket = s3.bucket("...")
val s3objs = bucket.keys("...").map( os => S3Object(bucket, os.getKey))
s3.deleteObjects(bucket, s3objs)
bucket.deleteObjects(s3objs)
Meta-data and content are automatically set to null.
=> S3 batch deletion fixes

src/main/scala/awscala/dynamodbv2/AttributeValue.scala, src/test/scala/awscala/DynamoDBV2Spec.scala
This project do not support a map inside a list/array but the DynamoDB does. Today the project supports only string set, number set or binary set.  This PR add the support (list of map) to AWScala lib.
Sample (`parsingErrors` attribute problem):
```json 
{
"client": "client-name",
"phase": "Finished",   
"parsingErrors": [
{
"line": 1,
"column": 2,
"msg": "there is a problem in XML"
}
],
"url": "http://testingurl.com/test-client.xml"
}
```
=> Add List with Map support to dynamodb v2

src/main/scala/awscala/sqs/Message.scala
Allows user to construct an awscala Message from an aws-sdk-java
Message without loosing the messageAttributes.
(Note messageAttributes and attributes are different).
=> SQS Message has messageAttributes

src/main/scala/awscala/dynamodbv2/AttributeValue.scala, src/main/scala/awscala/dynamodbv2/ResultPager.scala
This makes the `AttributeValue` constructor's arguments consistent.
Also removes the (now-redundant) fix introduced in [this commit](https://github.com/seratch/AWScala/commit/ed6b5c4e19d6e79efc895e5bd2a7d35751e39137).
Fixes #140
=> Add default value for AttributeValue's `l` field

README.md
Set the region in the S3 example to avoid confusion. My requests were timing out until I realized that I needed to set the region. I ended up finding the `at` method by looking at the S3.scala file
=> Set region in S3 example

src/main/scala/awscala/Region0.scala, src/test/scala/awscala/RegionSpec.scala
Also adds a test to ensure that the regions available in the AWS SDK are reflected on the Scala side.
Note that this does NOT update the AWS SDK to the latest (1.11.285). That version does not yet have `ap-northeast-3` available.
Fixes #142
=> Adds regions: Seoul, Mumbai, Ningxia, Canada, London, Paris, Ohio

core/src/main/scala/awscala/Region0.scala
The reference to `Region0` in the `awscala` package object will cause any usage of AWScala to throw
`java.lang.NoSuchFieldError: CN_NORTHWEST_1` in environments where the AWS SDK is not sufficiently up to date.
While usage of an SDK older than the one used to compile AWScala can never be guaranteed to work and is certainly not best practice, there are  practical situations where the user may not have
control of the SDK active in their JDK. One example is running a Spark application on AWS EMR.
EMR provides an Amazon-controlled installation of the AWS SDK that is added to Spark's extraClassPath and gets loaded in preference to any SDK bundled in the user's application jar.
By avoiding direct reference to the more recent region enum values, we decrease the chance of throwing errors in such …
=> Use string literals for regions recently added to AWS SDK

ec2/src/main/scala/awscala/ec2/Requests.scala
Modifications:
- Changed the deprecated `getIpRanges()` method to `getIpv4Ranges()`.
References:
- [EC2 - IpRange](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpRange.html)
=> Removed the usage of deprecated method.

core/src/main/scala/awscala/Region0.scala
It is related to #210.
If EMR version is low, IllegalArgumentException is raised.
It is because when calling the apply function by name as a string, if name is not in Regions, the exception is raised.
So, I've fixed the bug. In my code, when raising the exception, null is returned like "def apply(name: awsregions.Regions): Region".
email: keunhyun.oh@ahnlab.com
=> fix: "cannot create enum from eu-north-1-value"

dynamodb/src/main/scala/awscala/dynamodbv2/DynamoDB.scala, dynamodb/src/main/scala/awscala/dynamodbv2/Table.scala, dynamodb/src/test/scala/awscala/DynamoDBV2Spec.scala
This PR adds an overloaded method to DynamoDb to allow batch gets on tables with composite primary keys.
Some call outs:
1) I created two types: `SimplePk` and `CompositePk` in the DynamoDb companion
2) I added additional tests.
All tests are passing.
=> dynamo - batchget by composite key

build.sbt, ec2/src/main/scala/awscala/ec2/SSHEnabledInstance.scala, emr/src/test/scala/awscala/EMRSpec.scala, s3/src/main/scala/awscala/s3/S3.scala, s3/src/test/scala/awscala/S3Spec.scala
This doesn't add Scala 3 support for the DynamoDB module, as that uses reflection that would take more careful attention to port.
For the ec2 module it uses cross-version compatibility for the scala-ssh dependency. I've opened a [PR](https://github.com/sirthias/scala-ssh/pull/55) to build scala-ssh for Scala 3, but in the meantime the cross-version use shouldn't cause any problems for library users since scala-ssh doesn't bring in any transitive Scala-based dependencies.
=> Support Scala 3.0.0-RC3

README.md, build.sbt, dynamodb/src/main/scala-2/awscala/dynamodbv2/TableCompat.scala, dynamodb/src/main/scala-3/awscala/dynamodbv2/TableCompat.scala, dynamodb/src/main/scala/awscala/dynamodbv2/ResultPager.scala, dynamodb/src/main/scala/awscala/dynamodbv2/Table.scala, dynamodb/src/test/scala-2/awscala/DynamoDBV2AnnotationsSpec.scala, dynamodb/src/test/scala/awscala/DynamoDBV2Spec.scala
Adds Scala 3 support to all modules, with case class field annotations restricted to Scala 2 only. (I missed out the `core` and `ec2` modules in #251 🤦‍♂️ - adding Scala 3 to `core` produced some weird errors in `dynamodb`, so it seemed easiest to cross-build that too.)
Depends on #262
=> Scala 3.0.0

iam/src/main/scala/awscala/iam/AccessKey.scala, iam/src/test/scala/awscala/IAMSpec.scala
Hi!
This is a request to add the date created field for an access key. In the Java SDK that data comes from `.getCreateDate()`, and this PR is an attempt to add that information to this project. At the moment calling that function for an access key in this project will return `null`.
I don't have much experience with creating pull requests, so please let me know if I should change something and I will try my best :)
I added a simple test to see if the access key create date is approximately the same as when the test is being run. Best I could think of in this situation.
=> Add created date for IAM Access Keys
